name: my first workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4
        
        - name: List & Read file
          run: |
            echo "My first GitHub Actions Job"
            ls -larth
            cat README.md
        
#        - name: List files
#          run: ls -lrt
#
#        - name: Read the File
#          run: cat README.md
        
